version: '3.8'

services:
  tests:
    build: .
    volumes:
      - .:/app
    command: ["/root/.local/bin/poetry", "run", "pytest", "--maxfail=1", "--disable-warnings", "--html=reports/report.html"]
